In [1]:
import pandas as pd
import numpy as np
%matplotlib inline

In [2]:
dataset = pd.read_csv('heart.csv')

In [3]:
dataset.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [4]:
# from sklearn.preprocessing import MinMaxScaler

# scaler = MinMaxScaler()
# scaler.fit(dataset[['trestbps']])

# dataset['trestbps'] = scaler.transform(dataset[['trestbps']])

In [5]:
# scaler.fit(dataset[['chol']])

# dataset['chol'] = scaler.transform(dataset[['chol']])

In [6]:
# scaler.fit(dataset[['thalach']])

# dataset['thalach'] = scaler.transform(dataset[['thalach']])

In [7]:
# scaler.fit(dataset[['oldpeak']])

# dataset['oldpeak'] = scaler.transform(dataset[['oldpeak']])

In [8]:
dataset.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [9]:
dataset.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [10]:
c = 0
d = 0
for i in range(len(dataset['target'])):
    if dataset['target'][i] == 1:
        c = c+1
    elif dataset['target'][i] == 0:
        d = d+1

In [11]:
print(f"Occurence of 1 in Target : {c}\nOccurence of 0 in Target : {d}")
c , d

Occurence of 1 in Target : 165
Occurence of 0 in Target : 138


(165, 138)

In [12]:
dataset.shape

(303, 14)

In [13]:
dataset.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [14]:
dataset.drop(['age'] , axis=1, inplace=True)

In [15]:
dataset.head()

sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  ca  \
0    1   3       145   233    1        0      150      0      2.3      0   0   
1    1   2       130   250    0        1      187      0      3.5      0   0   
2    0   1       130   204    0        0      172      0      1.4      2   0   
3    1   1       120   236    0        1      178      0      0.8      2   0   
4    0   0       120   354    0        1      163      1      0.6      2   0   

   thal  target  
0     1       1  
1     2       1  
2     2       1  
3     2       1  
4     2       1

In [16]:
X = dataset.iloc[:,:-1]
Y = dataset.iloc[:,-1]

In [17]:
X.head()

sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  ca  \
0    1   3       145   233    1        0      150      0      2.3      0   0   
1    1   2       130   250    0        1      187      0      3.5      0   0   
2    0   1       130   204    0        0      172      0      1.4      2   0   
3    1   1       120   236    0        1      178      0      0.8      2   0   
4    0   0       120   354    0        1      163      1      0.6      2   0   

   thal  
0     1  
1     2  
2     2  
3     2  
4     2

In [18]:
Y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [19]:
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,-1].values

In [20]:
X

array([[  1.,   3., 145., ...,   0.,   0.,   1.],
       [  1.,   2., 130., ...,   0.,   0.,   2.],
       [  0.,   1., 130., ...,   2.,   0.,   2.],
       ...,
       [  1.,   0., 144., ...,   1.,   2.,   3.],
       [  1.,   0., 130., ...,   1.,   1.,   3.],
       [  0.,   1., 130., ...,   1.,   1.,   2.]])

In [21]:
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [22]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.25,random_state = 0)

In [23]:
from sklearn.preprocessing import StandardScaler

stc =StandardScaler()
X_train = stc.fit_transform(X_train)
X_test = stc.transform(X_test)

In [24]:
from sklearn.naive_bayes import GaussianNB

classifier = GaussianNB()
classifier.fit(X_train,Y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [25]:
y_pred = classifier.predict(X_test)

In [26]:
df = pd.DataFrame({'Actual':Y_test.flatten() , 'Predicted':y_pred.flatten()})

In [27]:
df.head(10)

Actual  Predicted
0       0          0
1       1          1
2       0          1
3       0          0
4       1          0
5       0          1
6       0          0
7       0          0
8       0          0
9       0          0

In [28]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report

print(f"Accuracy : \n{accuracy_score(Y_test,y_pred)*100}\n*********************************")
print(f"Confusion Matrix : \n{confusion_matrix(Y_test,y_pred)}\n*********************************")
print(f"Classification Report : \n{classification_report(Y_test,y_pred)}\n******************************************************************")

Accuracy : 
81.57894736842105
*********************************
Confusion Matrix : 
[[23 10]
 [ 4 39]]
*********************************
Classification Report : 
              precision    recall  f1-score   support

           0       0.85      0.70      0.77        33
           1       0.80      0.91      0.85        43

    accuracy                           0.82        76
   macro avg       0.82      0.80      0.81        76
weighted avg       0.82      0.82      0.81        76

******************************************************************
